//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailEnable.DeleteAccount.MePostOfficeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mailenable.com/MEWebAdminService/PostOffice", ConfigurationName="MePostOfficeService.PostOfficeSoap")]
    public interface PostOfficeSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/PostOffice/AddPostoffice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long AddPostoffice(string Account, string Name, long Status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/PostOffice/AddPostoffice", ReplyAction="*")]
        System.Threading.Tasks.Task<long> AddPostofficeAsync(string Account, string Name, long Status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/PostOffice/GetPostoffice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long GetPostoffice(string Account, string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/PostOffice/GetPostoffice", ReplyAction="*")]
        System.Threading.Tasks.Task<long> GetPostofficeAsync(string Account, string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/PostOffice/GetPostofficeObjectProperties", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        MailEnable.DeleteAccount.MePostOfficeService.GetPostofficeObjectPropertiesResponse GetPostofficeObjectProperties(MailEnable.DeleteAccount.MePostOfficeService.GetPostofficeObjectPropertiesRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/PostOffice/GetPostofficeObjectProperties", ReplyAction="*")]
        System.Threading.Tasks.Task<MailEnable.DeleteAccount.MePostOfficeService.GetPostofficeObjectPropertiesResponse> GetPostofficeObjectPropertiesAsync(MailEnable.DeleteAccount.MePostOfficeService.GetPostofficeObjectPropertiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/PostOffice/ListPostoffice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        MailEnable.DeleteAccount.MePostOfficeService.ListPostofficeResponse ListPostoffice(MailEnable.DeleteAccount.MePostOfficeService.ListPostofficeRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/PostOffice/ListPostoffice", ReplyAction="*")]
        System.Threading.Tasks.Task<MailEnable.DeleteAccount.MePostOfficeService.ListPostofficeResponse> ListPostofficeAsync(MailEnable.DeleteAccount.MePostOfficeService.ListPostofficeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/PostOffice/RemovePostoffice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        long RemovePostoffice(string Account, string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/PostOffice/RemovePostoffice", ReplyAction="*")]
        System.Threading.Tasks.Task<long> RemovePostofficeAsync(string Account, string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/PostOffice/EditPostoffice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        long EditPostoffice(string Account, string Name, string NewName, long NewStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/PostOffice/EditPostoffice", ReplyAction="*")]
        System.Threading.Tasks.Task<long> EditPostofficeAsync(string Account, string Name, string NewName, long NewStatus);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mailenable.com/MEWebAdminService/PostOffice")]
    public partial class Postoffice : MarshalByRefObject {
        
        private string nameField;
        
        private long statusField;
        
        private string accountField;
        
        private string hostField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
                this.RaisePropertyChanged("Account");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Host {
            get {
                return this.hostField;
            }
            set {
                this.hostField = value;
                this.RaisePropertyChanged("Host");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Postoffice))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mailenable.com/MEWebAdminService/PostOffice")]
    public abstract partial class MarshalByRefObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPostofficeObjectProperties", WrapperNamespace="http://mailenable.com/MEWebAdminService/PostOffice", IsWrapped=true)]
    public partial class GetPostofficeObjectPropertiesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/PostOffice", Order=0)]
        public string Account;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/PostOffice", Order=1)]
        public string Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/PostOffice", Order=2)]
        public MailEnable.DeleteAccount.MePostOfficeService.Postoffice ObjectProperties;
        
        public GetPostofficeObjectPropertiesRequest() {
        }
        
        public GetPostofficeObjectPropertiesRequest(string Account, string Name, MailEnable.DeleteAccount.MePostOfficeService.Postoffice ObjectProperties) {
            this.Account = Account;
            this.Name = Name;
            this.ObjectProperties = ObjectProperties;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPostofficeObjectPropertiesResponse", WrapperNamespace="http://mailenable.com/MEWebAdminService/PostOffice", IsWrapped=true)]
    public partial class GetPostofficeObjectPropertiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/PostOffice", Order=0)]
        public long GetPostofficeObjectPropertiesResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/PostOffice", Order=1)]
        public MailEnable.DeleteAccount.MePostOfficeService.Postoffice ObjectProperties;
        
        public GetPostofficeObjectPropertiesResponse() {
        }
        
        public GetPostofficeObjectPropertiesResponse(long GetPostofficeObjectPropertiesResult, MailEnable.DeleteAccount.MePostOfficeService.Postoffice ObjectProperties) {
            this.GetPostofficeObjectPropertiesResult = GetPostofficeObjectPropertiesResult;
            this.ObjectProperties = ObjectProperties;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListPostoffice", WrapperNamespace="http://mailenable.com/MEWebAdminService/PostOffice", IsWrapped=true)]
    public partial class ListPostofficeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/PostOffice", Order=0)]
        public MailEnable.DeleteAccount.MePostOfficeService.Postoffice[] ObjectList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/PostOffice", Order=1)]
        public string Account;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/PostOffice", Order=2)]
        public string Postoffice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/PostOffice", Order=3)]
        public long Top;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/PostOffice", Order=4)]
        public long MaxLength;
        
        public ListPostofficeRequest() {
        }
        
        public ListPostofficeRequest(MailEnable.DeleteAccount.MePostOfficeService.Postoffice[] ObjectList, string Account, string Postoffice, long Top, long MaxLength) {
            this.ObjectList = ObjectList;
            this.Account = Account;
            this.Postoffice = Postoffice;
            this.Top = Top;
            this.MaxLength = MaxLength;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListPostofficeResponse", WrapperNamespace="http://mailenable.com/MEWebAdminService/PostOffice", IsWrapped=true)]
    public partial class ListPostofficeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/PostOffice", Order=0)]
        public long ListPostofficeResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/PostOffice", Order=1)]
        public MailEnable.DeleteAccount.MePostOfficeService.Postoffice[] ObjectList;
        
        public ListPostofficeResponse() {
        }
        
        public ListPostofficeResponse(long ListPostofficeResult, MailEnable.DeleteAccount.MePostOfficeService.Postoffice[] ObjectList) {
            this.ListPostofficeResult = ListPostofficeResult;
            this.ObjectList = ObjectList;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PostOfficeSoapChannel : MailEnable.DeleteAccount.MePostOfficeService.PostOfficeSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PostOfficeSoapClient : System.ServiceModel.ClientBase<MailEnable.DeleteAccount.MePostOfficeService.PostOfficeSoap>, MailEnable.DeleteAccount.MePostOfficeService.PostOfficeSoap {
        
        public PostOfficeSoapClient() {
        }
        
        public PostOfficeSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PostOfficeSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PostOfficeSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PostOfficeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public long AddPostoffice(string Account, string Name, long Status) {
            return base.Channel.AddPostoffice(Account, Name, Status);
        }
        
        public System.Threading.Tasks.Task<long> AddPostofficeAsync(string Account, string Name, long Status) {
            return base.Channel.AddPostofficeAsync(Account, Name, Status);
        }
        
        public long GetPostoffice(string Account, string Name) {
            return base.Channel.GetPostoffice(Account, Name);
        }
        
        public System.Threading.Tasks.Task<long> GetPostofficeAsync(string Account, string Name) {
            return base.Channel.GetPostofficeAsync(Account, Name);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MailEnable.DeleteAccount.MePostOfficeService.GetPostofficeObjectPropertiesResponse MailEnable.DeleteAccount.MePostOfficeService.PostOfficeSoap.GetPostofficeObjectProperties(MailEnable.DeleteAccount.MePostOfficeService.GetPostofficeObjectPropertiesRequest request) {
            return base.Channel.GetPostofficeObjectProperties(request);
        }
        
        public long GetPostofficeObjectProperties(string Account, string Name, ref MailEnable.DeleteAccount.MePostOfficeService.Postoffice ObjectProperties) {
            MailEnable.DeleteAccount.MePostOfficeService.GetPostofficeObjectPropertiesRequest inValue = new MailEnable.DeleteAccount.MePostOfficeService.GetPostofficeObjectPropertiesRequest();
            inValue.Account = Account;
            inValue.Name = Name;
            inValue.ObjectProperties = ObjectProperties;
            MailEnable.DeleteAccount.MePostOfficeService.GetPostofficeObjectPropertiesResponse retVal = ((MailEnable.DeleteAccount.MePostOfficeService.PostOfficeSoap)(this)).GetPostofficeObjectProperties(inValue);
            ObjectProperties = retVal.ObjectProperties;
            return retVal.GetPostofficeObjectPropertiesResult;
        }
        
        public System.Threading.Tasks.Task<MailEnable.DeleteAccount.MePostOfficeService.GetPostofficeObjectPropertiesResponse> GetPostofficeObjectPropertiesAsync(MailEnable.DeleteAccount.MePostOfficeService.GetPostofficeObjectPropertiesRequest request) {
            return base.Channel.GetPostofficeObjectPropertiesAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MailEnable.DeleteAccount.MePostOfficeService.ListPostofficeResponse MailEnable.DeleteAccount.MePostOfficeService.PostOfficeSoap.ListPostoffice(MailEnable.DeleteAccount.MePostOfficeService.ListPostofficeRequest request) {
            return base.Channel.ListPostoffice(request);
        }
        
        public long ListPostoffice(ref MailEnable.DeleteAccount.MePostOfficeService.Postoffice[] ObjectList, string Account, string Postoffice, long Top, long MaxLength) {
            MailEnable.DeleteAccount.MePostOfficeService.ListPostofficeRequest inValue = new MailEnable.DeleteAccount.MePostOfficeService.ListPostofficeRequest();
            inValue.ObjectList = ObjectList;
            inValue.Account = Account;
            inValue.Postoffice = Postoffice;
            inValue.Top = Top;
            inValue.MaxLength = MaxLength;
            MailEnable.DeleteAccount.MePostOfficeService.ListPostofficeResponse retVal = ((MailEnable.DeleteAccount.MePostOfficeService.PostOfficeSoap)(this)).ListPostoffice(inValue);
            ObjectList = retVal.ObjectList;
            return retVal.ListPostofficeResult;
        }
        
        public System.Threading.Tasks.Task<MailEnable.DeleteAccount.MePostOfficeService.ListPostofficeResponse> ListPostofficeAsync(MailEnable.DeleteAccount.MePostOfficeService.ListPostofficeRequest request) {
            return base.Channel.ListPostofficeAsync(request);
        }
        
        public long RemovePostoffice(string Account, string Name) {
            return base.Channel.RemovePostoffice(Account, Name);
        }
        
        public System.Threading.Tasks.Task<long> RemovePostofficeAsync(string Account, string Name) {
            return base.Channel.RemovePostofficeAsync(Account, Name);
        }
        
        public long EditPostoffice(string Account, string Name, string NewName, long NewStatus) {
            return base.Channel.EditPostoffice(Account, Name, NewName, NewStatus);
        }
        
        public System.Threading.Tasks.Task<long> EditPostofficeAsync(string Account, string Name, string NewName, long NewStatus) {
            return base.Channel.EditPostofficeAsync(Account, Name, NewName, NewStatus);
        }
    }
}
