//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailEnable.DeleteAccount.MeMailBoxService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mailenable.com/MEWebAdminService/Mailbox", ConfigurationName="MeMailBoxService.MailboxSoap")]
    public interface MailboxSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Mailbox/AddMailbox", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long AddMailbox(string Postoffice, string MailboxName, long Status, long Limit, long RedirectStatus, string RedirectAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Mailbox/AddMailbox", ReplyAction="*")]
        System.Threading.Tasks.Task<long> AddMailboxAsync(string Postoffice, string MailboxName, long Status, long Limit, long RedirectStatus, string RedirectAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Mailbox/GetMailbox", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long GetMailbox(string Postoffice, string MailboxName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Mailbox/GetMailbox", ReplyAction="*")]
        System.Threading.Tasks.Task<long> GetMailboxAsync(string Postoffice, string MailboxName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Mailbox/GetMailboxObjectProperties", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        MailEnable.DeleteAccount.MeMailBoxService.GetMailboxObjectPropertiesResponse GetMailboxObjectProperties(MailEnable.DeleteAccount.MeMailBoxService.GetMailboxObjectPropertiesRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Mailbox/GetMailboxObjectProperties", ReplyAction="*")]
        System.Threading.Tasks.Task<MailEnable.DeleteAccount.MeMailBoxService.GetMailboxObjectPropertiesResponse> GetMailboxObjectPropertiesAsync(MailEnable.DeleteAccount.MeMailBoxService.GetMailboxObjectPropertiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Mailbox/ListMailbox", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        MailEnable.DeleteAccount.MeMailBoxService.ListMailboxResponse ListMailbox(MailEnable.DeleteAccount.MeMailBoxService.ListMailboxRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Mailbox/ListMailbox", ReplyAction="*")]
        System.Threading.Tasks.Task<MailEnable.DeleteAccount.MeMailBoxService.ListMailboxResponse> ListMailboxAsync(MailEnable.DeleteAccount.MeMailBoxService.ListMailboxRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Mailbox/RemoveMailbox", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        long RemoveMailbox(string Postoffice, string MailboxName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Mailbox/RemoveMailbox", ReplyAction="*")]
        System.Threading.Tasks.Task<long> RemoveMailboxAsync(string Postoffice, string MailboxName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Mailbox/EditMailbox", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        long EditMailbox(string Postoffice, string MailboxName, string NewMailboxName, long NewStatus, long NewSize, long NewLimit, long NewRedirectStatus, string NewRedirectAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Mailbox/EditMailbox", ReplyAction="*")]
        System.Threading.Tasks.Task<long> EditMailboxAsync(string Postoffice, string MailboxName, string NewMailboxName, long NewStatus, long NewSize, long NewLimit, long NewRedirectStatus, string NewRedirectAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Mailbox/GetAutoResponderContents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        string GetAutoResponderContents(string Postoffice, string MailboxName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Mailbox/GetAutoResponderContents", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetAutoResponderContentsAsync(string Postoffice, string MailboxName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Mailbox/GetAutoResponderStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        long GetAutoResponderStatus(string Postoffice, string MailboxName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Mailbox/GetAutoResponderStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<long> GetAutoResponderStatusAsync(string Postoffice, string MailboxName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Mailbox/GetAutoResponderSubject", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        string GetAutoResponderSubject(string Postoffice, string MailboxName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Mailbox/GetAutoResponderSubject", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetAutoResponderSubjectAsync(string Postoffice, string MailboxName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Mailbox/GetAutoSignatureStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        long GetAutoSignatureStatus(string Account, string Mailbox);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Mailbox/GetAutoSignatureStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<long> GetAutoSignatureStatusAsync(string Account, string Mailbox);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Mailbox/GetQuota", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        long GetQuota(string Postoffice, string MailboxName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Mailbox/GetQuota", ReplyAction="*")]
        System.Threading.Tasks.Task<long> GetQuotaAsync(string Postoffice, string MailboxName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Mailbox/GetSignature", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        string GetSignature(string Postoffice, string MailboxName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Mailbox/GetSignature", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetSignatureAsync(string Postoffice, string MailboxName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Mailbox/GetSize", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        long GetSize(string Postoffice, string MailboxName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Mailbox/GetSize", ReplyAction="*")]
        System.Threading.Tasks.Task<long> GetSizeAsync(string Postoffice, string MailboxName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Mailbox/SetAutoResponderContents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        long SetAutoResponderContents(string Postoffice, string MailboxName, string Header, string MessageBody);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Mailbox/SetAutoResponderContents", ReplyAction="*")]
        System.Threading.Tasks.Task<long> SetAutoResponderContentsAsync(string Postoffice, string MailboxName, string Header, string MessageBody);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Mailbox/SetAutoResponderDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        long SetAutoResponderDetails(string Postoffice, string MailboxName, string Subject, string MessageBody);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Mailbox/SetAutoResponderDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<long> SetAutoResponderDetailsAsync(string Postoffice, string MailboxName, string Subject, string MessageBody);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Mailbox/SetAutoResponderStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        long SetAutoResponderStatus(string Postoffice, string MailboxName, long Status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Mailbox/SetAutoResponderStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<long> SetAutoResponderStatusAsync(string Postoffice, string MailboxName, long Status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Mailbox/SetAutoSignatureStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        long SetAutoSignatureStatus(string Account, string MailboxName, long Status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Mailbox/SetAutoSignatureStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<long> SetAutoSignatureStatusAsync(string Account, string MailboxName, long Status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Mailbox/SetSignature", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        long SetSignature(string Postoffice, string MailboxName, string NewSignature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Mailbox/SetSignature", ReplyAction="*")]
        System.Threading.Tasks.Task<long> SetSignatureAsync(string Postoffice, string MailboxName, string NewSignature);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mailenable.com/MEWebAdminService/Mailbox")]
    public partial class Mailbox : MarshalByRefObject {
        
        private string postofficeField;
        
        private string mailboxNameField;
        
        private string redirectAddressField;
        
        private long redirectStatusField;
        
        private long statusField;
        
        private long limitField;
        
        private long sizeField;
        
        private string hostField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Postoffice {
            get {
                return this.postofficeField;
            }
            set {
                this.postofficeField = value;
                this.RaisePropertyChanged("Postoffice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MailboxName {
            get {
                return this.mailboxNameField;
            }
            set {
                this.mailboxNameField = value;
                this.RaisePropertyChanged("MailboxName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RedirectAddress {
            get {
                return this.redirectAddressField;
            }
            set {
                this.redirectAddressField = value;
                this.RaisePropertyChanged("RedirectAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long RedirectStatus {
            get {
                return this.redirectStatusField;
            }
            set {
                this.redirectStatusField = value;
                this.RaisePropertyChanged("RedirectStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long Limit {
            get {
                return this.limitField;
            }
            set {
                this.limitField = value;
                this.RaisePropertyChanged("Limit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
                this.RaisePropertyChanged("Size");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Host {
            get {
                return this.hostField;
            }
            set {
                this.hostField = value;
                this.RaisePropertyChanged("Host");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Mailbox))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mailenable.com/MEWebAdminService/Mailbox")]
    public abstract partial class MarshalByRefObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMailboxObjectProperties", WrapperNamespace="http://mailenable.com/MEWebAdminService/Mailbox", IsWrapped=true)]
    public partial class GetMailboxObjectPropertiesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/Mailbox", Order=0)]
        public string Postoffice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/Mailbox", Order=1)]
        public string MailboxName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/Mailbox", Order=2)]
        public MailEnable.DeleteAccount.MeMailBoxService.Mailbox ObjectProperties;
        
        public GetMailboxObjectPropertiesRequest() {
        }
        
        public GetMailboxObjectPropertiesRequest(string Postoffice, string MailboxName, MailEnable.DeleteAccount.MeMailBoxService.Mailbox ObjectProperties) {
            this.Postoffice = Postoffice;
            this.MailboxName = MailboxName;
            this.ObjectProperties = ObjectProperties;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMailboxObjectPropertiesResponse", WrapperNamespace="http://mailenable.com/MEWebAdminService/Mailbox", IsWrapped=true)]
    public partial class GetMailboxObjectPropertiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/Mailbox", Order=0)]
        public long GetMailboxObjectPropertiesResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/Mailbox", Order=1)]
        public MailEnable.DeleteAccount.MeMailBoxService.Mailbox ObjectProperties;
        
        public GetMailboxObjectPropertiesResponse() {
        }
        
        public GetMailboxObjectPropertiesResponse(long GetMailboxObjectPropertiesResult, MailEnable.DeleteAccount.MeMailBoxService.Mailbox ObjectProperties) {
            this.GetMailboxObjectPropertiesResult = GetMailboxObjectPropertiesResult;
            this.ObjectProperties = ObjectProperties;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListMailbox", WrapperNamespace="http://mailenable.com/MEWebAdminService/Mailbox", IsWrapped=true)]
    public partial class ListMailboxRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/Mailbox", Order=0)]
        public MailEnable.DeleteAccount.MeMailBoxService.Mailbox[] ObjectList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/Mailbox", Order=1)]
        public string Postoffice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/Mailbox", Order=2)]
        public long Top;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/Mailbox", Order=3)]
        public long MaxLength;
        
        public ListMailboxRequest() {
        }
        
        public ListMailboxRequest(MailEnable.DeleteAccount.MeMailBoxService.Mailbox[] ObjectList, string Postoffice, long Top, long MaxLength) {
            this.ObjectList = ObjectList;
            this.Postoffice = Postoffice;
            this.Top = Top;
            this.MaxLength = MaxLength;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListMailboxResponse", WrapperNamespace="http://mailenable.com/MEWebAdminService/Mailbox", IsWrapped=true)]
    public partial class ListMailboxResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/Mailbox", Order=0)]
        public long ListMailboxResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/Mailbox", Order=1)]
        public MailEnable.DeleteAccount.MeMailBoxService.Mailbox[] ObjectList;
        
        public ListMailboxResponse() {
        }
        
        public ListMailboxResponse(long ListMailboxResult, MailEnable.DeleteAccount.MeMailBoxService.Mailbox[] ObjectList) {
            this.ListMailboxResult = ListMailboxResult;
            this.ObjectList = ObjectList;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MailboxSoapChannel : MailEnable.DeleteAccount.MeMailBoxService.MailboxSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MailboxSoapClient : System.ServiceModel.ClientBase<MailEnable.DeleteAccount.MeMailBoxService.MailboxSoap>, MailEnable.DeleteAccount.MeMailBoxService.MailboxSoap {
        
        public MailboxSoapClient() {
        }
        
        public MailboxSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MailboxSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailboxSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailboxSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public long AddMailbox(string Postoffice, string MailboxName, long Status, long Limit, long RedirectStatus, string RedirectAddress) {
            return base.Channel.AddMailbox(Postoffice, MailboxName, Status, Limit, RedirectStatus, RedirectAddress);
        }
        
        public System.Threading.Tasks.Task<long> AddMailboxAsync(string Postoffice, string MailboxName, long Status, long Limit, long RedirectStatus, string RedirectAddress) {
            return base.Channel.AddMailboxAsync(Postoffice, MailboxName, Status, Limit, RedirectStatus, RedirectAddress);
        }
        
        public long GetMailbox(string Postoffice, string MailboxName) {
            return base.Channel.GetMailbox(Postoffice, MailboxName);
        }
        
        public System.Threading.Tasks.Task<long> GetMailboxAsync(string Postoffice, string MailboxName) {
            return base.Channel.GetMailboxAsync(Postoffice, MailboxName);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MailEnable.DeleteAccount.MeMailBoxService.GetMailboxObjectPropertiesResponse MailEnable.DeleteAccount.MeMailBoxService.MailboxSoap.GetMailboxObjectProperties(MailEnable.DeleteAccount.MeMailBoxService.GetMailboxObjectPropertiesRequest request) {
            return base.Channel.GetMailboxObjectProperties(request);
        }
        
        public long GetMailboxObjectProperties(string Postoffice, string MailboxName, ref MailEnable.DeleteAccount.MeMailBoxService.Mailbox ObjectProperties) {
            MailEnable.DeleteAccount.MeMailBoxService.GetMailboxObjectPropertiesRequest inValue = new MailEnable.DeleteAccount.MeMailBoxService.GetMailboxObjectPropertiesRequest();
            inValue.Postoffice = Postoffice;
            inValue.MailboxName = MailboxName;
            inValue.ObjectProperties = ObjectProperties;
            MailEnable.DeleteAccount.MeMailBoxService.GetMailboxObjectPropertiesResponse retVal = ((MailEnable.DeleteAccount.MeMailBoxService.MailboxSoap)(this)).GetMailboxObjectProperties(inValue);
            ObjectProperties = retVal.ObjectProperties;
            return retVal.GetMailboxObjectPropertiesResult;
        }
        
        public System.Threading.Tasks.Task<MailEnable.DeleteAccount.MeMailBoxService.GetMailboxObjectPropertiesResponse> GetMailboxObjectPropertiesAsync(MailEnable.DeleteAccount.MeMailBoxService.GetMailboxObjectPropertiesRequest request) {
            return base.Channel.GetMailboxObjectPropertiesAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MailEnable.DeleteAccount.MeMailBoxService.ListMailboxResponse MailEnable.DeleteAccount.MeMailBoxService.MailboxSoap.ListMailbox(MailEnable.DeleteAccount.MeMailBoxService.ListMailboxRequest request) {
            return base.Channel.ListMailbox(request);
        }
        
        public long ListMailbox(ref MailEnable.DeleteAccount.MeMailBoxService.Mailbox[] ObjectList, string Postoffice, long Top, long MaxLength) {
            MailEnable.DeleteAccount.MeMailBoxService.ListMailboxRequest inValue = new MailEnable.DeleteAccount.MeMailBoxService.ListMailboxRequest();
            inValue.ObjectList = ObjectList;
            inValue.Postoffice = Postoffice;
            inValue.Top = Top;
            inValue.MaxLength = MaxLength;
            MailEnable.DeleteAccount.MeMailBoxService.ListMailboxResponse retVal = ((MailEnable.DeleteAccount.MeMailBoxService.MailboxSoap)(this)).ListMailbox(inValue);
            ObjectList = retVal.ObjectList;
            return retVal.ListMailboxResult;
        }
        
        public System.Threading.Tasks.Task<MailEnable.DeleteAccount.MeMailBoxService.ListMailboxResponse> ListMailboxAsync(MailEnable.DeleteAccount.MeMailBoxService.ListMailboxRequest request) {
            return base.Channel.ListMailboxAsync(request);
        }
        
        public long RemoveMailbox(string Postoffice, string MailboxName) {
            return base.Channel.RemoveMailbox(Postoffice, MailboxName);
        }
        
        public System.Threading.Tasks.Task<long> RemoveMailboxAsync(string Postoffice, string MailboxName) {
            return base.Channel.RemoveMailboxAsync(Postoffice, MailboxName);
        }
        
        public long EditMailbox(string Postoffice, string MailboxName, string NewMailboxName, long NewStatus, long NewSize, long NewLimit, long NewRedirectStatus, string NewRedirectAddress) {
            return base.Channel.EditMailbox(Postoffice, MailboxName, NewMailboxName, NewStatus, NewSize, NewLimit, NewRedirectStatus, NewRedirectAddress);
        }
        
        public System.Threading.Tasks.Task<long> EditMailboxAsync(string Postoffice, string MailboxName, string NewMailboxName, long NewStatus, long NewSize, long NewLimit, long NewRedirectStatus, string NewRedirectAddress) {
            return base.Channel.EditMailboxAsync(Postoffice, MailboxName, NewMailboxName, NewStatus, NewSize, NewLimit, NewRedirectStatus, NewRedirectAddress);
        }
        
        public string GetAutoResponderContents(string Postoffice, string MailboxName) {
            return base.Channel.GetAutoResponderContents(Postoffice, MailboxName);
        }
        
        public System.Threading.Tasks.Task<string> GetAutoResponderContentsAsync(string Postoffice, string MailboxName) {
            return base.Channel.GetAutoResponderContentsAsync(Postoffice, MailboxName);
        }
        
        public long GetAutoResponderStatus(string Postoffice, string MailboxName) {
            return base.Channel.GetAutoResponderStatus(Postoffice, MailboxName);
        }
        
        public System.Threading.Tasks.Task<long> GetAutoResponderStatusAsync(string Postoffice, string MailboxName) {
            return base.Channel.GetAutoResponderStatusAsync(Postoffice, MailboxName);
        }
        
        public string GetAutoResponderSubject(string Postoffice, string MailboxName) {
            return base.Channel.GetAutoResponderSubject(Postoffice, MailboxName);
        }
        
        public System.Threading.Tasks.Task<string> GetAutoResponderSubjectAsync(string Postoffice, string MailboxName) {
            return base.Channel.GetAutoResponderSubjectAsync(Postoffice, MailboxName);
        }
        
        public long GetAutoSignatureStatus(string Account, string Mailbox) {
            return base.Channel.GetAutoSignatureStatus(Account, Mailbox);
        }
        
        public System.Threading.Tasks.Task<long> GetAutoSignatureStatusAsync(string Account, string Mailbox) {
            return base.Channel.GetAutoSignatureStatusAsync(Account, Mailbox);
        }
        
        public long GetQuota(string Postoffice, string MailboxName) {
            return base.Channel.GetQuota(Postoffice, MailboxName);
        }
        
        public System.Threading.Tasks.Task<long> GetQuotaAsync(string Postoffice, string MailboxName) {
            return base.Channel.GetQuotaAsync(Postoffice, MailboxName);
        }
        
        public string GetSignature(string Postoffice, string MailboxName) {
            return base.Channel.GetSignature(Postoffice, MailboxName);
        }
        
        public System.Threading.Tasks.Task<string> GetSignatureAsync(string Postoffice, string MailboxName) {
            return base.Channel.GetSignatureAsync(Postoffice, MailboxName);
        }
        
        public long GetSize(string Postoffice, string MailboxName) {
            return base.Channel.GetSize(Postoffice, MailboxName);
        }
        
        public System.Threading.Tasks.Task<long> GetSizeAsync(string Postoffice, string MailboxName) {
            return base.Channel.GetSizeAsync(Postoffice, MailboxName);
        }
        
        public long SetAutoResponderContents(string Postoffice, string MailboxName, string Header, string MessageBody) {
            return base.Channel.SetAutoResponderContents(Postoffice, MailboxName, Header, MessageBody);
        }
        
        public System.Threading.Tasks.Task<long> SetAutoResponderContentsAsync(string Postoffice, string MailboxName, string Header, string MessageBody) {
            return base.Channel.SetAutoResponderContentsAsync(Postoffice, MailboxName, Header, MessageBody);
        }
        
        public long SetAutoResponderDetails(string Postoffice, string MailboxName, string Subject, string MessageBody) {
            return base.Channel.SetAutoResponderDetails(Postoffice, MailboxName, Subject, MessageBody);
        }
        
        public System.Threading.Tasks.Task<long> SetAutoResponderDetailsAsync(string Postoffice, string MailboxName, string Subject, string MessageBody) {
            return base.Channel.SetAutoResponderDetailsAsync(Postoffice, MailboxName, Subject, MessageBody);
        }
        
        public long SetAutoResponderStatus(string Postoffice, string MailboxName, long Status) {
            return base.Channel.SetAutoResponderStatus(Postoffice, MailboxName, Status);
        }
        
        public System.Threading.Tasks.Task<long> SetAutoResponderStatusAsync(string Postoffice, string MailboxName, long Status) {
            return base.Channel.SetAutoResponderStatusAsync(Postoffice, MailboxName, Status);
        }
        
        public long SetAutoSignatureStatus(string Account, string MailboxName, long Status) {
            return base.Channel.SetAutoSignatureStatus(Account, MailboxName, Status);
        }
        
        public System.Threading.Tasks.Task<long> SetAutoSignatureStatusAsync(string Account, string MailboxName, long Status) {
            return base.Channel.SetAutoSignatureStatusAsync(Account, MailboxName, Status);
        }
        
        public long SetSignature(string Postoffice, string MailboxName, string NewSignature) {
            return base.Channel.SetSignature(Postoffice, MailboxName, NewSignature);
        }
        
        public System.Threading.Tasks.Task<long> SetSignatureAsync(string Postoffice, string MailboxName, string NewSignature) {
            return base.Channel.SetSignatureAsync(Postoffice, MailboxName, NewSignature);
        }
    }
}
